#!/usr/bin/env bash

# Disable pseudo-TTY allocation for CI. The -T flag removes interaction.
TTY=""

# Travis CI provides a CI environment variable which can be used to check if
# this is running in a CI environment.
if [[ ${CI:-false} == "true" ]]; then
    TTY="-T"
fi

# Pass arguments to docker-compose, or default to docker-compose ps.
if [[ $# -gt 0  ]]; then
    case "$1" in

        art|artisan )
            shift 1
            docker-compose run --rm ${TTY} \
                app \
                php artisan "$@"
            ;;

        composer )
            shift 1
            docker-compose run --rm ${TTY} \
                app \
                composer "$@"
            ;;

        npm )
            shift 1
            docker-compose run --rm ${TTY} \
                node \
                npm "$@"
            ;;

        * ) docker-compose "$@"; ;;

    esac
else
    docker-compose ps
fi
