version: "3"

services:
  app:
    image: the-leeds-repo/api/app
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-net
    ports:
      - "${APP_PORT:-80}:80"
    command: /usr/bin/supervisord

  queue-worker:
    image: the-leeds-repo/api/app
    volumes:
      - .:/var/www/html
    networks:
      - app-net
    command: php artisan queue:work --tries=1

  scheduler:
    image: the-leeds-repo/api/app
    volumes:
      - .:/var/www/html
    networks:
      - app-net
    command: php artisan tlr:run-scheduler

  node:
    image: the-leeds-repo/api/node
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS:-secret}"
      MYSQL_DATABASE: "${DB_NAME:-the_leeds_repo}"
      MYSQL_USER: "${DB_USER:-the_leeds_repo}"
      MYSQL_PASSWORD: "${DB_PASS:-secret}"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-net
    ports:
      - "${DB_PORT:-3306}:3306"

  mysql-testing:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASS:-secret}"
      MYSQL_DATABASE: "${DB_NAME:-the_leeds_repo}"
      MYSQL_USER: "${DB_USER:-the_leeds_repo}"
      MYSQL_PASSWORD: "${DB_PASS:-secret}"
    networks:
      - app-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
    environment:
      discovery-type: single-node
    networks:
      - app-net
    ports:
      - "${ELASTICSEARCH_PORT:-9200}:9200"

networks:
  app-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local
